### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by werdeil**
As promise here is the PR to add the French translation

Note: There are some strings not present in the string.txt:
- `Choose genres to exclude` visible in the plugin settings
- All playlist names (stored in the `*.sql.xml` files)

I don't know if it is possible to handle them in the string.txt file but without it the translation may feel odd (see below)
image

### CODE REVIEW

**Comment by AF-1** [comment]
Thank you for translating all of that. Unfortunately, I think you're right: a semi-translated plugin would feel weird, wrong. And the translation problems wouldn't even stop at the names of the now 188 built-in playlists. You have playlist parameters in most lists, i.e. names and the different values they can take - which would be more difficult to parse. 
In the end I don't think the benefit of localized/translated strings is really worth the added complexity and effort.
So if you don't mind I'm going to close this PR for now.

**Comment by werdeil** [comment]
I'll try to see if there is a way to have the translation of some parts without the "weird" feeling. Because I really like having the translation on the main menu and in the settings.
So don't close it, but don't merge it either for now.

**Comment by AF-1** [comment]
Ok, I'm working on a localization of **built-in** playlist names, param names and param values. In the end it might not be 100% but probably close. So just wait for now. I'll upload once I'm through and you can base your next commit on that.
BTW please don't delete the multiple blank lines in strings.txt and other files. They're there to visually delineate different parts and make finding specific parts easier. Thanks.

**Comment by werdeil** [comment]
> I'm working on a localization of built-in playlist names, param names and param values

Ok I'll wait for it.

> BTW please don't delete the multiple blank lines in strings.txt and other files.

Sorry, I didn't think that it was intended, I'll make sure to put everything back in the next commit.

**Comment by AF-1** [comment]
Made built-in playlist names and param (value) names localizable.
Just use the latest strings.txt to insert the translated FR strings. It already includes the missing blank lines.
There are many new strings. Hope I didn't miss any. Take your time translating and testing. There's no hurry at all.

P.S. [Special characters recommendations](https://github.com/AF-1/lms-dynamicplaylists#translation) may be helpful, e.g. right single quotation mark instead of apostrophe etc.

**Comment by werdeil** [comment]
Ok I'll work on it. You may get update in this PR at each of my intermediate commits, but wait for my go before reviewing it.

**Comment by AF-1** [comment]
The strings.txt changed with the last commit. Let me know when you think the FR translation is ready and I'll roll out an update.

**Comment by werdeil** [comment]
@AF-1 I updated to the last version of your code and proof read all strings. For me you can merge it.

**Comment by AF-1** [comment]
Thank you for your translation.

**Pull request merged**
